language: python

# use caching to speed up builds
cache: pip

python:
  - 3.6

install:
  # install the core climate_indices package
  - pip install .

  # install packages required for test coverage and reporting via Coveralls
  - pip install coverage
  - pip install coveralls

script:
  # run all tests with coverage
  #- coverage run --source=climate_indices setup.py test
  - pytest

after_success:
  # produce a code coverage report for coveralls.io integration
  - coveralls

# don't email after every build success/failure
notifications:
  email: false
